#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32g
#SBATCH --time=06:00:00
#SBATCH --job-name=survivor_bat
#SBATCH --output=/gpfs01/home/mbxas26/CNS/logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/home/mbxas26/CNS/logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxas26@exmail.nottingham.ac.uk

# load environment
source "$HOME/.bash_profile"
conda activate survivor

# -------- inputs (BATMAN) --------
SNIFFLES_VCF="/gpfs01/home/mbxas26/CNS/epi2me_bat/sniffles/output_rnames.vcf"
CUTESV_VCF="/gpfs01/home/mbxas26/CNS/cuteSV/output/bat.vcf"
SVIM_VCF="/gpfs01/home/mbxas26/CNS/svim/output/variants.vcf"

# -------- outputs --------
OUTDIR="/gpfs01/home/mbxas26/CNS/merged/batman"
mkdir -p "$OUTDIR"
LIST="${OUTDIR}/input_files.txt"
MERGED_VCF="${OUTDIR}/batman_merged.vcf"

# -------- SURVIVOR merge ----------
SURVIVOR merge "$LIST" 500 2 1 1 0 30 "$MERGED_VCF"

# -------- split by SVTYPE ----------
for T in DEL DUP INV BND; do
  OUT="${OUTDIR}/batman_${T}.vcf"
  bcftools view -i "INFO/SVTYPE==\"${T}\"" "$MERGED_VCF" -o "$OUT" -O v
  bgzip -f "$OUT"
  tabix -f -p vcf "${OUT}.gz"
done

bgzip -f "$MERGED_VCF"
tabix -f -p vcf "${MERGED_VCF}.gz"

# decativate environment after completion
conda deactivate
