#!/bin/bash

#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=128g
#SBATCH --time=48:00:00
#SBATCH --job-name=epi2me
#SBATCH --output=/gpfs01/home/mbxas26/CNS/epi2me/logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/home/mbxas26/CNS/epi2me/logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxas26@exmail.nottingham.ac.uk

source $HOME/.bash_profile

conda activate nextflow

# load modules
module load singularity/3.8.5  #load module

cd /gpfs01/home/mbxas26/CNS/project_files  #path to files

nextflow run epi2me-labs/wf-human-variation -r v2.6.0 \    #nextflow command
        --bam '/gpfs01/home/mbxas26/CNS/project_files/sort_25D016162.bam' \   #path to bam file
        --ref '/gpfs01/home/mbxas26/CNS/project_files/Homo_sapiens.GRCh38.dna.primary_assembly.fa' \   #path to reference file
        --bed '/gpfs01/home/mbxas26/CNS/project_files/sort_25D016162.validated.bed' \   #path to bed file
        --sample_name 'CNS' \   #name of sample
        --snp \  #single nucleotide polymorphism
        --sv \   #structural variants
        --cnv \  #copy number variants
        --mod \  #modified bases
        --bam_min_coverage 1.0 \   #min coverage for a bam file to show variants
        --phased \   #performs phasing
        --out_dir '/gpfs01/home/mbxas26/CNS/epi2me' \  #path to output directory
        -profile singularity

conda deactivate
